let firstNumber = 6;
let secondNumber = 2;
let Number3 = 11;
let Number4 = 3;
let Number5 = 8;
let Number6 = 1;
let Number7 = 40;
let Number8 = 5;
let addResult = firstNumber + secondNumber;
let subtractResult = Number3 - Number4;
let multiplyResult = Number5 * Number6;
let divideResult = Number7 / Number8;
console.log(`Addition of ${firstNumber} and ${secondNumber} is: ` + addResult);
console.log(`Subtraction of ${Number3} and ${Number4} is: ` + subtractResult);
console.log(`Multiplication of ${Number5} and ${Number6} is: ` + multiplyResult);
console.log(`Division of ${Number7} and ${Number8} is: ` + divideResult);
console.log("console.log(5+3)=  " + (5 + 3));
console.log("console.log(11-3)=  " + (11 - 3));
console.log("console.log(4 x 2)=  " + (4 * 2));
console.log("console.log(40 / 5)=  " + (40 / 5));
export {};
